# Generated by Django 2.2.7 on 2020-04-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
