# Generated by Django 2.2.7 on 2020-04-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0005_auto_20200418_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
