# Generated by Django 2.2.7 on 2020-04-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0007_auto_20200418_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name_plural': 'dishes'},
        ),
    ]
