# Generated by Django 2.2.7 on 2020-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0010_auto_20200419_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default='', on_delete=None, related_name='products', to='info_rest.Category'),
        ),
    ]
