# Generated by Django 2.2.7 on 2020-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0013_auto_20200420_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='uploads/Dino2.jpg', upload_to='uploads/'),
        ),
    ]
