# Generated by Django 2.2.7 on 2020-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0016_auto_20200420_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
