# Generated by Django 2.2.7 on 2020-04-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0017_userprofile_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
