# Generated by Django 2.2.7 on 2020-04-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0019_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid',
        ),
    ]
