# Generated by Django 2.2.7 on 2020-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_rest', '0021_auto_20200501_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=35)),
            ],
        ),
    ]
