# Generated by Django 2.2.7 on 2020-04-27 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200427_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 19, 59, 25, 612104)),
        ),
    ]
